### PR TITLE
Update documentation for multiple selection

### PR DESCRIPTION
**Pull request by firezym**
Update documentation for multiple selection, including:
1. gif demonstration
2. mentioning it in doc

### CODE REVIEW

**Comment by parmentelat** [comment]
oops I forgot to push my latest commits...
would you care to rebase on top of the latest main ?
my bad...

**Comment by firezym** [comment]
no problem. I will sync again.

**Comment by firezym** [comment]
Is there a need to rebase? Just now I have merged your newest commits. Seems no conflicts. I think maybe we can pass the check now.

**Comment by parmentelat** [comment]
yeah I meant to rebase, not to merge
never mind, I did it on my end, no worries
will issue 0.2.4 shortly

**Comment by firezym** [comment]
@parmentelat It seems that your README.md page is not updated of the newest gif demo. My PR is 4 commits ahead. What should I do to help sync?

**Comment by parmentelat** [comment]
hey @firezym 

3 things:

- first, the content is fine; it's true that the multi-cell sequence comes very (too ?) late in the gif, but please double-check, it's there; it came as part of my rebase with commit a500d0d
- second, I had again forgotten to push the very last commit 47fb0be, I just did that; mind you, it was just about the new release numbers...
- last, as I said I rebased the repo on my end, so you have to give up on your merge !
  otherwise you're going to weave a branch that is endlessly parallel to mine...
  if you're not too fluent with git the simplest is maybe to just trash your fork and create a new one..

**Comment by firezym** [comment]
@parmentelat I checked all the changes. It is already the newest in your repo. So I just deleted my fork ... too complicated for me to understand the parallel universe ... maybe I should ask Loki about it later... lol,

**Comment by parmentelat** [comment]
sounds about right ! thanks

**Pull request closed without merging**
