### PR TITLE
add drop down menu for commands

### PR DESCRIPTION
**Pull request by firezym**
1. add button (original split cell extension style) and a drop down menu for commands using menu of lumino widgets
2. optimize the desription for commands

Already test it by uninstalling and re-installing from git remote repo as a clean start. Pls check and test it further.

image

### CODE REVIEW

**Comment by firezym** [comment]
Have no clue what's wrong. It worked fine in my env. Please check @parmentelat 
image

**Comment by parmentelat** [comment]
just run `jlpm run lint` and commit any change

**Comment by parmentelat** [comment]
thanks, will issue a new release shortly

**Comment by parmentelat** [comment]
0.1.4 is up at pypi !

**Comment by firezym** [comment]
Cool !

**Comment by parmentelat** [comment]
it took me some trial and error cycles to finally get it right wrt multiple notebooks opened at the same time

hopefully version 0.2.1 should be quite fine now, please try to shake it up as much as you can :-)

I know of one remaining issue #7, so if you see it and can help pinpoint how to reproduce, please comment on that one

**Pull request merged**
